model:
  arch: m000_unet
  params:
    channels: [32, 128, 512]
    num_blocks_per_stage: 2
    num_bottleneck_resblocks: 2
    embed_dim: 256

dataset:
  name: cifar10
  train:
    imgsize: 32
    batchsize: 64
    n_workers: 8
  val:
    imgsize: 32
    batchsize: 32
    n_workers: 4

training:
  log_freq: 200
  tb_log_freq: 20
  # Probability of dropping CLS conditioning.
  # Needed to enable CFG.
  cfg_dropout_prob: 0.1

validation:
  val_iters: 5000
  sample_num_steps: 20
  sample_cfg_scale: 2.0
  log_sample_num_imgs: 10

fid:
  enabled: True
  num_samples: 10000
  batch_size: 32
  cfg_scale: 1.0

lr: 2.0e-4
weight_decay: 1.e-6
grad_clip_norm: 5.0
train_iters: 200000
warmup_iters: 2000
scheduler: 'cosine'
amp:
  enabled: true
